services:
  # PGW Сервер
  pgw_server:
    build:
      context: .
      target: server
      args:
        BUILD_TYPE: Release
    container_name: pgw_server
    ports:
      - "9000:9000/udp"
      - "9090:9090/tcp"
      - "8080:8080/tcp"
    volumes:
      - ./configs:/app/configs:ro
      - pgw_logs:/app/logs
      - pgw_cdr:/app/cdr
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    healthcheck:
      # Здесь мы просто отправляем тетсовую команду серверу, чтобы проверить запустился ли он
      test: ["CMD", "curl", "-f", "http://localhost:8080/check_subscriber?imsi=001010123456789"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pgw_network

  # PGW Клиент (для тестирования)
  pgw_client:
    build:
      context: .
      target: client
    container_name: pgw_client
    depends_on:
      pgw_server:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs:ro
      - pgw_logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    profiles:
      - manual
    networks:
      - pgw_network

  # Тестовый прогонщик (опционально)
  test_runner:
    build:
      context: .
      target: testing
    container_name: pgw_tests
    working_dir: /tests
    volumes:
      - ./configs:/tests/configs:ro
      - pgw_logs:/tests/logs
    environment:
      - TZ=Europe/Moscow
    profiles:
      - test
    networks:
      - pgw_network

networks:
  pgw_network:
    driver: bridge

volumes:
  pgw_logs:
  pgw_cdr:
